/**
 * Created by Dmytro.Pavlenko on 17.02.2017.
 */

export const GET_ROUTES_REQUEST = 'GET_ROUTES_REQUEST';
export const GET_ROUTES_SUCCESS = 'GET_ROUTES_SUCCESS';
export const GET_ROUTES_FAIL = 'GET_ROUTES_FAIL';

export const GET_ROUTES_DEVICES_REQUEST = 'GET_ROUTES_DEVICES_REQUEST';
export const GET_ROUTES_DEVICES_SUCCESS = 'GET_ROUTES_DEVICES_SUCCESS';
export const GET_ROUTES_DEVICES_FAIL = 'GET_ROUTES_DEVICES_FAIL';

export const ADD_ROUTE_POINT = 'ADD_ROUTE_POINT';
export const REMOVE_ROUTE_POINT = 'REMOVE_ROUTE_POINT';
