/**
 * Created by Dmytro.Pavlenko on 17.02.2017.
 */

export const GET_ROUTES_REQUEST = 'GET_ROUTES_REQUEST';
export const GET_ROUTES_SUCCESS = 'GET_ROUTES_SUCCESS';
export const GET_ROUTES_FAIL = 'GET_ROUTES_FAIL';

export const GET_ROUTES_DEVICES_REQUEST = 'GET_ROUTES_DEVICES_REQUEST';
export const GET_ROUTES_DEVICES_SUCCESS = 'GET_ROUTES_DEVICES_SUCCESS';
export const GET_ROUTES_DEVICES_FAIL = 'GET_ROUTES_DEVICES_FAIL';

export const ADD_ROUTE_POINT = 'ADD_ROUTE_POINT';
export const REMOVE_ROUTE_POINT = 'REMOVE_ROUTE_POINT';

export const ADD_OBSERVABLE_POINT = 'ADD_OBSERVABLE_POINT';
export const START_SELECTING_OBSERVABLES = 'START_SELECTING_OBSERVABLES';
export const STOP_SELECTING_OBSERVABLES = 'STOP_SELECTING_OBSERVABLES';
export const REMOVE_OBSERVABLE_POINT  = 'REMOVE_OBSERVABLE_POINT';

export const CALCULATE_DISTANCE_BETWEEN_CHECKPOINTS = 'CALCULATE_DISTANCE_BETWEEN_CHECKPOINTS';
